---
all:
  vars:
    ansible_become: True
    ansible_become_method: enable
  children:
    ios_nodes:
      vars:
        ansible_network_os: ios
        ansible_user: cisco
        ansible_password: cisco
      hosts:
        R1:
          ansible_host: 192.168.137.233
        R4:
          ansible_host: 192.168.137.235
        R5:
          ansible_host: 192.168.137.236
    eos_nodes:
      vars:
        ansible_network_os: eos
        ansible_user: arista
        ansible_password: arista
      hosts:
        veos1:
          ansible_host: 192.168.137.231
        veos2:
          ansible_host: 192.168.137.232
