---
all:
  children:
    web_servers:
      hosts:
        my_web_server_01:
          ansible_host: 10.1.1.1
        my_web_server_02:
          ansible_host: 10.1.1.2
        my_web_server_03:
          ansible_host: 10.1.1.3
    app_servers:
      hosts:
        my_app_server_01:
          ansible_host: 10.1.2.1
        my_app_server_02:
          ansible_host: 10.1.2.2
        my_app_server_03:
          ansible_host: 10.1.2.3

