---
R01:
  hostname: '10.1.1.1'
  port: '22'
  username: 'cisco'
  password: 'cisco'
  platform: 'cisco_ios'

R02: 
  hostname: '10.1.1.2'  
  port: '22'
  username: 'cisco'
  password: 'cisco'
  platform: 'cisco_ios'

R03:
  hostname: '10.1.1.3'
  port: '22'
  username: 'cisco'
  password: 'cisco'
  platform: 'cisco_ios'

R04:
  hostname: '10.1.1.4'
  port: '22'
  username: 'cisco'
  password: 'cisco'
  platform: 'cisco_ios'

R05:
  hostname: '10.1.1.5'
  port: '22'
  username: 'cisco'
  password: 'cisco'
  platform: 'cisco_ios'
