---
all:
  children:
    metallb:
      children:
        spines:
          hosts:
            spine01:
              ansible_host: 192.168.137.221
              ansible_network_os: ios
            spine02:
              ansible_host: 192.168.137.222
              ansible_network_os: ios
        leafs:
          hosts:
            leaf01:
              ansible_host: 192.168.137.223
              ansible_network_os: eos
            leaf02:
              ansible_host: 192.168.137.224
              ansible_network_os: eos
        nodes:
          hosts:
            node1:
              ansible_host: 192.168.137.225
              ansible_network_os: ios
            node2:
              ansible_host: 192.168.137.226
              ansible_network_os: ios
            node3:
              ansible_host: 192.168.137.227
              ansible_network_os: ios
